version: '3'

services:
  migration:
    build: .
    env_file: .env
    command: python manage.py migrate
    volumes:
      - .:/usr/src/apps/cityhallmonitor
  static:
    build: .
    env_file: .env
    command: python manage.py collectstatic --noinput
    volumes:
      - .:/usr/src/apps/cityhallmonitor
      - web-static:/var/www/cityhallmonitor/static
  app:
    build: .
    env_file: .env
    restart: always
    volumes:
      - .:/usr/src/apps/cityhallmonitor
      - web-static:/var/www/cityhallmonitor/static
    environment:
      DEBUG: 'true'
      PYTHONPATH: .
    command: gunicorn --workers 3 --worker-tmp-dir /dev/shm --bind unix:/usr/src/apps/cityhallmonitor/mnt/cityhallmonitor.sock core.wsgi:application
    depends_on:
      - migration
      - static

volumes:
  web-django:
  web-static:
