version: '3'

services:
  migration:
    build: .
    env_file: .env
    run: python manage.py migrate
    volumes:
      - .:/usr/src/apps/cityhallmonitor
  static:
    build: .
    env_file: .env
    run: python manage.py collectstatic --noinput
    volumes:
      - .:/usr/src/apps/cityhallmonitor
      - /var/www/cityhallmonitor:/var/www/cityhallmonitor
  app:
    build: .
    env_file: .env
    restart: always
    volumes:
      - .:/usr/src/apps/cityhallmonitor
      - /var/www/cityhallmonitor:/var/www/cityhallmonitor
    environment:
      DEBUG: 'true'
      PYTHONPATH: .
    command: gunicorn --workers 3 --worker-tmp-dir /dev/shm --bind unix:/usr/src/apps/cityhallmonitor/mnt/cityhallmonitor.sock core.wsgi:application
    depends_on:
      - migration
      - static

volumes:
  web-django:
  web-static:
