version: '3'

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - web-static:/usr/src/static
    env_file: .env
    environment:
      DEBUG: 'true'
      PYTHONPATH: .:$PYTHONPATH
    command: /usr/local/bin/gunicorn core.wsgi:application -w 2 -b :8000 --reload
    depends_on:
      - postgres

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: cityhallmonitor_dev
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  web-static:
  pgdata:
