project_name: cityhallmonitor
service_name: apps/cityhallmonitor
port: 9017
staticdir: "{{ ansible_env.TMPDIR }}/cityhallmonitor_static"
virtualenv: "/home/apps/env/{{ project_name }}"
django: true

install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
project_repo: git@github.com:NUKnightLab/cityhallmonitor.git

system_packages:
  - git
  - nginx
  - postgresql
  - python-pip
  - python-dev
  - python-psycopg2
