project_name: cityhallmonitor

wsgi_env_common:
  DJANGO_SETTINGS_MODULE: "core.settings.{{ env }}"
  SECRET_KEY: "{{ vault_secret_key }}"
  DOCUMENT_CLOUD_USERNAME: "{{ vault_document_cloud_username }}"
  DOCUMENT_CLOUD_PASSWORD: "{{ vault_document_cloud_password }}"
  DOCUMENT_CLOUD_ACCOUNT: "{{ vault_document_cloud_account }}"
  DOCUMENT_CLOUD_PROJECT: "{{ vault_document_cloud_project }}"
  EMAIL_HOST_USER: "{{ vault_email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ vault_email_host_password }}"

port: 9017
python: python3
type: django
django_settings_module: core.settings.{{ env }}

# Configs below will not usually change
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
deploy_dir: "{{ install_root }}/{{ project_name }}"
django_root: ""
requirements_file: "{{ deploy_dir }}/requirements.txt"
service_name: "apps/{{ project_name }}"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "{{ deploy_config_dir }}.wsgi:application"
