domains: "{{ project_name }}.knightlab.com"

#static_bucket: "media.knightlab.com"
gunicorn_reload: False
service_exec: "{{ virtualenv}}/bin/gunicorn -b :{{ service_port }} --workers 3 {{ wsgi_application }}"

ssl:
  ssl_certificate: "/etc/nginx/ssl/knightlab/knightlab-bundle.crt"
  ssl_certificate_key: "/etc/nginx/ssl/knightlab/knightlab-com.key"

#init_env_prd:
#  STATIC_URL: "//media.knightlab.com/{{ project_name }}/"

#init_env: "{{ init_env_common|combine(init_env_prd) }}"
init_env: "{{ init_env_common }}"
