project_name: cityhallmonitor
gitdeploy_version: "1.0.6"
python_version: "3.8.2"
python: /home/apps/sites/cityhallmonitor/.venv/bin/python
service_port: "{{ cityhallmonitor_port }}"

# The deploy-static playbook is here for demo purposes and configured in stg
# only. S3 static is not used by this project.

playbooks:
  - playbook.deploy-repo.yml
  - playbook.deploy-web.yml



# env vars

init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DJANGO_SETTINGS_MODULE: "core.settings.ec2"
  STATIC_ROOT: "/var/www/{{ project_name }}/static"
  DJANGO_SECRET_KEY: "{{ vault_django_secret_key }}"
  DOCUMENT_CLOUD_USERNAME: "{{ vault_document_cloud_username }}"
  DOCUMENT_CLOUD_PASSWORD: "{{ vault_document_cloud_password }}"
  DOCUMENT_CLOUD_ACCOUNT: "{{ vault_document_cloud_account }}"
  DOCUMENT_CLOUD_PROJECT: "{{ vault_document_cloud_project }}"
  EMAIL_HOST_USER: "{{ vault_email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ vault_email_host_password }}"
  DB_ENGINE__DEFAULT: "django.db.backends.postgresql_psycopg2"
  DB_NAME__DEFAULT: "{{ project_name }}_{{ env }}"
  DB_USER__DEFAULT: "{{ vault_db_user__default }}"
  DB_PASSWORD__DEFAULT: "{{ vault_db_password__default }}"
  DB_HOST__DEFAULT: "{{ vault_db_host__default }}"
  DB_PORT__DEFAULT: "{{ vault_db_port__default }}"



# paths

install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
nginx_conf: "{{ deploy_dir }}/nginx/conf.d/{{ project_name }}.conf"

# s3 sync config for demo purposes. Not used by project

s3_src_dir: "/var/www/{{ project_name }}"
s3_dest: "s3://{{ static_bucket }}/{{ project_name }}"


