project_name: cityhallmonitor
static_tmpdir: "/tmp/{{ project_name }}_static"

# these will be merged with deployment-specific env into init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"
  APPLICATION_DOMAINS: "{{ domains }}" # space-delimited
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  STATIC_TMPDIR: "{{ static_tmpdir }}"
  DJANGO_SECRET_KEY: "{{ vault_django_secret_key }}"
  DOCUMENT_CLOUD_USERNAME: "{{ vault_document_cloud_username }}"
  DOCUMENT_CLOUD_PASSWORD: "{{ vault_document_cloud_password }}"
  DOCUMENT_CLOUD_ACCOUNT: "{{ vault_document_cloud_account }}"
  DOCUMENT_CLOUD_PROJECT: "{{ vault_document_cloud_project }}"
  EMAIL_HOST_USER: "{{ vault_email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ vault_email_host_password }}"
  DB_ENGINE__DEFAULT: "django.db.backends.postgresql_psycopg2"
  DB_NAME__DEFAULT: "{{ project_name }}_{{ env }}"
  DB_USER__DEFAULT: "{{ vault_db_user__default }}"
  DB_PASSWORD__DEFAULT: "{{ vault_db_password__default }}"
  DB_HOST__DEFAULT: "{{ vault_db_host__default }}"
  DB_PORT__DEFAULT: "{{ vault_db_port__default }}"

port: 9017
python: python3
type: django
django_settings_module: core.settings.ec2

# Configs below will not usually change
project_repo: "git@github.com:NUKnightLab/{{ project_name }}.git"
deploy_dir: "{{ install_root }}/{{ project_name }}"
app_dir: "{{ deploy_dir }}" # application dir could be a subdirectory
requirements_file: "{{ deploy_dir }}/requirements.txt"
service_name: "apps/{{ project_name }}"
virtualenv: "{{ virtualenv_root }}/{{ project_name }}"
wsgi_application: "core.wsgi:application"
env_setup_script: "{{ deploy_dir }}/env.sh"
