project_name: cityhallmonitor

gunicorn_env:
  - DJANGO_SETTINGS_MODULE=core.settings.{{ env }}
port: 9017
python: python3
type: django

# Configs below will not usually change
project_repo: git@github.com:NUKnightLab/{{ project_name }}.git
application_user: apps
deploy_dir: "{{ install_root }}/{{ project_name }}"
install_root: /home/apps/sites
service_name: apps/{{ project_name }}
virtualenv: /home/apps/env/{{ project_name }}
wsgi_application: "conf.{{ env }}.wsgi:application"
