# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
                ('active_flag', models.IntegerField()),
                ('used_flag', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.CharField(max_length=255)),
                ('meet_flag', models.IntegerField()),
                ('active_flag', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('used_control_flag', models.IntegerField()),
                ('n_members', models.IntegerField()),
                ('used_acting_flag', models.IntegerField()),
                ('used_target_flag', models.IntegerField()),
                ('used_sponsor_flag', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'BodyType',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('date', models.DateField()),
                ('time', models.TextField(blank=True)),
                ('video_status', models.TextField(blank=True)),
                ('agenda_status_id', models.IntegerField(null=True)),
                ('agenda_status_name', models.TextField(blank=True)),
                ('minutes_status_id', models.IntegerField(null=True)),
                ('minutes_status_name', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='cityhallmonitor.Body')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('agenda_sequence', models.IntegerField()),
                ('minutes_sequence', models.IntegerField()),
                ('agenda_number', models.TextField(default='', blank=True)),
                ('video', models.IntegerField(default=0)),
                ('video_index', models.IntegerField(default=0)),
                ('version', models.TextField(default='', blank=True)),
                ('agenda_note', models.TextField(default='', blank=True)),
                ('minutes_note', models.TextField(default='', blank=True)),
                ('passed_flag', models.IntegerField(default=0)),
                ('passed_flag_name', models.TextField(default='', blank=True)),
                ('roll_call_flag', models.IntegerField(default=0)),
                ('flag_extra', models.IntegerField(default=0)),
                ('title', models.TextField(default='', blank=True)),
                ('tally', models.TextField(default='', blank=True)),
                ('consent', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='cityhallmonitor.Action')),
                ('event', models.ForeignKey(to='cityhallmonitor.Event')),
            ],
            options={
                'ordering': ['agenda_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('file', models.TextField()),
                ('name', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('intro_date', models.DateTimeField(null=True)),
                ('agenda_date', models.DateTimeField(null=True)),
                ('passed_date', models.DateTimeField(null=True)),
                ('enactment_date', models.DateTimeField(null=True)),
                ('enactment_number', models.TextField(blank=True)),
                ('requester', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('version', models.TextField(blank=True)),
                ('text1', models.TextField(blank=True)),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('text4', models.TextField(blank=True)),
                ('text5', models.TextField(blank=True)),
                ('date1', models.DateTimeField(null=True)),
                ('date2', models.DateTimeField(null=True)),
                ('ex_text1', models.TextField(blank=True)),
                ('ex_text2', models.TextField(blank=True)),
                ('ex_text3', models.TextField(blank=True)),
                ('ex_text4', models.TextField(blank=True)),
                ('ex_text5', models.TextField(blank=True)),
                ('ex_text6', models.TextField(blank=True)),
                ('ex_text7', models.TextField(blank=True)),
                ('ex_text8', models.TextField(blank=True)),
                ('ex_text9', models.TextField(blank=True)),
                ('ex_text10', models.TextField(blank=True)),
                ('ex_date1', models.DateTimeField(null=True)),
                ('ex_date2', models.DateTimeField(null=True)),
                ('ex_date3', models.DateTimeField(null=True)),
                ('ex_date4', models.DateTimeField(null=True)),
                ('ex_date5', models.DateTimeField(null=True)),
                ('ex_date6', models.DateTimeField(null=True)),
                ('ex_date7', models.DateTimeField(null=True)),
                ('ex_date8', models.DateTimeField(null=True)),
                ('ex_date9', models.DateTimeField(null=True)),
                ('ex_date10', models.DateTimeField(null=True)),
                ('body', models.ForeignKey(to='cityhallmonitor.Body')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatterAttachment',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
                ('hyperlink', models.TextField(blank=True)),
                ('file_name', models.TextField(blank=True)),
                ('matter_version', models.TextField(blank=True)),
                ('is_hyperlink', models.BooleanField()),
                ('is_supporting_doc', models.BooleanField()),
                ('binary', models.TextField(default='', blank=True)),
                ('matter', models.ForeignKey(to='cityhallmonitor.Matter')),
            ],
            options={
                'verbose_name': 'MatterAttachment',
            },
        ),
        migrations.CreateModel(
            name='MatterSponsor',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('matter_version', models.TextField(default='0', blank=True)),
                ('sequence', models.IntegerField()),
                ('matter', models.ForeignKey(to='cityhallmonitor.Matter')),
            ],
            options={
                'verbose_name': 'MatterSponsor',
            },
        ),
        migrations.CreateModel(
            name='MatterStatus',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField()),
                ('active_flag', models.IntegerField()),
                ('used_flag', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MatterStatuses',
                'ordering': ['name', 'sort'],
                'verbose_name': 'MatterStatus',
            },
        ),
        migrations.CreateModel(
            name='MatterType',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('sort', models.IntegerField()),
                ('active_flag', models.IntegerField()),
                ('used_flag', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'MatterTypes',
                'ordering': ['name', 'sort'],
                'verbose_name': 'MatterType',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField()),
                ('full_name', models.TextField()),
                ('active_flag', models.IntegerField()),
                ('used_sponsor_flag', models.IntegerField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('guid', models.CharField(max_length=100, blank=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('row_version', models.CharField(max_length=100, blank=True)),
                ('name', models.TextField()),
                ('plural_name', models.TextField()),
                ('used_for', models.IntegerField()),
                ('result', models.IntegerField()),
                ('sort', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'sort'],
                'verbose_name': 'VoteType',
            },
        ),
        migrations.AddField(
            model_name='mattersponsor',
            name='person',
            field=models.ForeignKey(to='cityhallmonitor.Person'),
        ),
        migrations.AddField(
            model_name='matter',
            name='matter_status',
            field=models.ForeignKey(to='cityhallmonitor.MatterStatus'),
        ),
        migrations.AddField(
            model_name='matter',
            name='matter_type',
            field=models.ForeignKey(to='cityhallmonitor.MatterType'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='cityhallmonitor.Matter'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='mover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, related_name='mover', blank=True, to='cityhallmonitor.Person'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='seconder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, related_name='seconder', blank=True, to='cityhallmonitor.Person'),
        ),
        migrations.AddField(
            model_name='body',
            name='body_type',
            field=models.ForeignKey(to='cityhallmonitor.BodyType'),
        ),
        migrations.AddField(
            model_name='body',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='cityhallmonitor.Person'),
        ),
    ]
